spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: inventory
          uri: lb://INVENTORY
          predicates:
            - Path=/api/inventory/**
        - id: orders
          uri: lb://ORDERS
          predicates:
            - Path=/api/orders/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
